<<<<<<< HEAD
import os
from pathlib import Path
import dj_database_url
from decouple import config
=======
"""
Django settings for blog_site project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

>>>>>>> production

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = False  # Make sure debug is turned off for production

<<<<<<< HEAD
# ALLOWED_HOSTS: Allow all hosts to avoid issues on Vercel (you can restrict it later)
ALLOWED_HOSTS = ['*']
=======
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['your-vercel-domain.vercel.app', 'localhost']

>>>>>>> production

# SECURITY SETTINGS
SECURE_SSL_REDIRECT = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Whitenoise for static files
    'posts',  # Your app
    'users',  # Your app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise middleware for serving static files
]

ROOT_URLCONF = 'blog_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [BASE_DIR / 'templates'],  # Make sure templates path is correct
=======
        # 'DIRS': ['templates'],
        'DIRS': [BASE_DIR / 'templates'],
>>>>>>> production
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_site.wsgi.application'

<<<<<<< HEAD
# Database Configuration: Use PostgreSQL from Railway
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='postgres://user:password@localhost/dbname')
    )
=======

# Database
DATABASES = {
    'default': dj_database_url.config(default=config('DATABASE_URL'))
>>>>>>> production
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
<<<<<<< HEAD

# Ensure that Whitenoise can serve static files in production
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Whitenoise will collect static files here
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Ensure media is correctly mapped
=======
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# For media files (if used)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
>>>>>>> production

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set secret key from environment variables (for security)
SECRET_KEY = config('DJANGO_SECRET_KEY')

# For serverless: manage database connections (important in a serverless environment)
if 'VERCEL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        default=config('DATABASE_URL')
    )
